const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  Header, Footer, AlignmentType, HeadingLevel, BorderStyle, WidthType,
  ShadingType, VerticalAlign, PageNumber, PageBreak, LevelFormat,
  ExternalHyperlink
} = require('docx');
const fs = require('fs');

// ─── helpers ────────────────────────────────────────────────────────────────
const border = { style: BorderStyle.SINGLE, size: 1, color: 'BBBBBB' };
const borders = { top: border, bottom: border, left: border, right: border };
const noBorder = { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' };
const noBorders = { top: noBorder, bottom: noBorder, left: noBorder, right: noBorder };

function h1(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_1,
    spacing: { before: 360, after: 120 },
    children: [new TextRun({ text, bold: true, size: 36, color: '1B5E20', font: 'Arial' })]
  });
}
function h2(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_2,
    spacing: { before: 240, after: 80 },
    children: [new TextRun({ text, bold: true, size: 28, color: '2E7D32', font: 'Arial' })]
  });
}
function h3(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_3,
    spacing: { before: 180, after: 60 },
    children: [new TextRun({ text, bold: true, size: 24, color: '388E3C', font: 'Arial' })]
  });
}
function p(text, opts = {}) {
  return new Paragraph({
    spacing: { before: 60, after: 100 },
    alignment: opts.center ? AlignmentType.CENTER : AlignmentType.BOTH,
    children: [new TextRun({ text, size: 22, font: 'Arial', ...opts })]
  });
}
function pb() {
  return new Paragraph({ children: [new PageBreak()] });
}
function space(n = 1) {
  return new Paragraph({ spacing: { before: 0, after: n * 80 }, children: [new TextRun('')] });
}
function bullet(text, level = 0) {
  return new Paragraph({
    numbering: { reference: 'bullets', level },
    spacing: { before: 40, after: 40 },
    children: [new TextRun({ text, size: 22, font: 'Arial' })]
  });
}
function num(text, level = 0) {
  return new Paragraph({
    numbering: { reference: 'numbers', level },
    spacing: { before: 40, after: 40 },
    children: [new TextRun({ text, size: 22, font: 'Arial' })]
  });
}

function codeBlock(lines) {
  const cLines = Array.isArray(lines) ? lines : lines.split('\n');
  return new Table({
    width: { size: 9026, type: WidthType.DXA },
    columnWidths: [9026],
    rows: [new TableRow({
      children: [new TableCell({
        borders,
        width: { size: 9026, type: WidthType.DXA },
        shading: { fill: 'F1F8E9', type: ShadingType.CLEAR },
        margins: { top: 120, bottom: 120, left: 180, right: 180 },
        children: cLines.map(line => new Paragraph({
          spacing: { before: 0, after: 0 },
          children: [new TextRun({ text: line || ' ', font: 'Courier New', size: 18, color: '1A1A1A' })]
        }))
      })]
    })]
  });
}

function infoBox(title, text, color = 'E8F5E9') {
  return new Table({
    width: { size: 9026, type: WidthType.DXA },
    columnWidths: [9026],
    rows: [new TableRow({
      children: [new TableCell({
        borders,
        width: { size: 9026, type: WidthType.DXA },
        shading: { fill: color, type: ShadingType.CLEAR },
        margins: { top: 120, bottom: 120, left: 200, right: 200 },
        children: [
          new Paragraph({ children: [new TextRun({ text: title, bold: true, size: 22, font: 'Arial', color: '1B5E20' })] }),
          new Paragraph({ children: [new TextRun({ text, size: 21, font: 'Arial' })] })
        ]
      })]
    })]
  });
}

function twoCol(label, value) {
  return new Table({
    width: { size: 9026, type: WidthType.DXA },
    columnWidths: [3000, 6026],
    rows: [new TableRow({
      children: [
        new TableCell({
          borders,
          width: { size: 3000, type: WidthType.DXA },
          shading: { fill: 'C8E6C9', type: ShadingType.CLEAR },
          margins: { top: 80, bottom: 80, left: 120, right: 120 },
          children: [new Paragraph({ children: [new TextRun({ text: label, bold: true, size: 20, font: 'Arial' })] })]
        }),
        new TableCell({
          borders,
          width: { size: 6026, type: WidthType.DXA },
          margins: { top: 80, bottom: 80, left: 120, right: 120 },
          children: [new Paragraph({ children: [new TextRun({ text: value, size: 20, font: 'Arial' })] })]
        })
      ]
    })]
  });
}

// ─── DOCUMENT ────────────────────────────────────────────────────────────────
const doc = new Document({
  numbering: {
    config: [
      { reference: 'bullets', levels: [{ level: 0, format: LevelFormat.BULLET, text: '•', alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } } } }, { level: 1, format: LevelFormat.BULLET, text: '◦', alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 1080, hanging: 360 } } } }] },
      { reference: 'numbers', levels: [{ level: 0, format: LevelFormat.DECIMAL, text: '%1.', alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } } } }] }
    ]
  },
  styles: {
    default: { document: { run: { font: 'Arial', size: 22 } } },
    paragraphStyles: [
      { id: 'Heading1', name: 'Heading 1', basedOn: 'Normal', next: 'Normal', quickFormat: true, run: { size: 36, bold: true, font: 'Arial', color: '1B5E20' }, paragraph: { spacing: { before: 360, after: 120 }, outlineLevel: 0 } },
      { id: 'Heading2', name: 'Heading 2', basedOn: 'Normal', next: 'Normal', quickFormat: true, run: { size: 28, bold: true, font: 'Arial', color: '2E7D32' }, paragraph: { spacing: { before: 240, after: 80 }, outlineLevel: 1 } },
      { id: 'Heading3', name: 'Heading 3', basedOn: 'Normal', next: 'Normal', quickFormat: true, run: { size: 24, bold: true, font: 'Arial', color: '388E3C' }, paragraph: { spacing: { before: 180, after: 60 }, outlineLevel: 2 } },
    ]
  },
  sections: [{
    properties: {
      page: {
        size: { width: 11906, height: 16838 },
        margin: { top: 1440, right: 1200, bottom: 1440, left: 1440 }
      }
    },
    headers: {
      default: new Header({
        children: [new Paragraph({
          alignment: AlignmentType.RIGHT,
          border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: '2E7D32', space: 4 } },
          children: [new TextRun({ text: 'Астық Мерке — Веб-сайт жасау жобасы | Техникалық есеп', size: 18, font: 'Arial', color: '2E7D32', italics: true })]
        })]
      })
    },
    footers: {
      default: new Footer({
        children: [new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [
            new TextRun({ text: '© 2026 Астық Мерке  |  Бет ', size: 18, font: 'Arial', color: '888888' }),
            new TextRun({ children: [PageNumber.CURRENT], size: 18, font: 'Arial', color: '888888' }),
          ]
        })]
      })
    },
    children: [

      // ══════════════════════════════════════════
      // ТИТУЛЬНЫЙ ЛИСТ
      // ══════════════════════════════════════════
      space(4),
      new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 0, after: 40 }, children: [new TextRun({ text: '🌾', size: 80 })] }),
      new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 0, after: 120 }, children: [new TextRun({ text: 'АСТЫҚ МЕРКЕ', bold: true, size: 56, font: 'Arial', color: '1B5E20' })] }),
      new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 0, after: 200 }, children: [new TextRun({ text: 'Агро Кешенінің Ресми Веб-сайтын Жасау', size: 30, font: 'Arial', color: '388E3C', italics: true })] }),
      new Table({
        width: { size: 7000, type: WidthType.DXA },
        columnWidths: [7000],
        rows: [new TableRow({ children: [new TableCell({
          borders,
          width: { size: 7000, type: WidthType.DXA },
          shading: { fill: 'E8F5E9', type: ShadingType.CLEAR },
          margins: { top: 200, bottom: 200, left: 300, right: 300 },
          children: [
            new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: 'ТЕХНИКАЛЫҚ ЕСЕП', bold: true, size: 32, font: 'Arial', color: '1B5E20' })] }),
            space(1),
            new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: 'Веб-сайт жасаудың толық сипаттамасы', size: 22, font: 'Arial', color: '555555', italics: true })] }),
            space(1),
            new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: 'Жасаған: Боранқұлов Ерасыл', bold: true, size: 24, font: 'Arial', color: '2E7D32' })] }),
            new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: 'Жыл: 2026', size: 22, font: 'Arial', color: '555555' })] }),
            new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: 'Сайт мекенжайы: merke-agro.vercel.app', size: 22, font: 'Arial', color: '1565C0' })] }),
          ]
        })] })]
      }),
      pb(),

      // ══════════════════════════════════════════
      // МАЗМҰНЫ
      // ══════════════════════════════════════════
      h1('МАЗМҰНЫ'),
      space(1),
      ...['1. Жобаға кіріспе', '2. Пайдаланылған құралдар мен технологиялар', '3. Жоба құрылымы', '4. 1-қадам: Git репозиторийін дайындау', '5. 2-қадам: HTML — index.html файлын жасау', '6. 3-қадам: CSS — main.css стильдер', '7. 4-қадам: JavaScript — data.js деректер', '8. 5-қадам: JavaScript — app.js қосымша логикасы', '9. 6-қадам: Serverless API — api/save.js', '10. 7-қадам: Serverless API — api/submit.js', '11. 8-қадам: GitHub-қа жариялау', '12. 9-қадам: Vercel-де орналастыру', '13. 10-қадам: Орта айнымалылары (Environment Variables)', '14. Тестілеу және қателерді жою', '15. Қорытынды'].map(item =>
        new Paragraph({ spacing: { before: 40, after: 40 }, children: [new TextRun({ text: item, size: 22, font: 'Arial' })] })
      ),
      pb(),

      // ══════════════════════════════════════════
      // 1. КІРІСПЕ
      // ══════════════════════════════════════════
      h1('1. ЖОБАҒА КІРІСПЕ'),
      p('Бұл техникалық есеп «Астық Мерке» агро кешенінің ресми веб-сайтын жасау барысын толық сипаттайды. Сайтты жасауда заманауи веб-технологиялар — HTML5, CSS3, JavaScript — пайдаланылды, ал контентті басқару үшін GitHub API негізінде кастомды CMS жүйесі және Vercel serverless функциялары енгізілді.'),
      space(1),
      h2('1.1 Жоба мақсаты'),
      p('Жоба мақсаты — «Астық Мерке» агро кешенінің өнімдері мен қызметтерін үш тілде (қазақ, орыс, ағылшын) таныстыратын, мобильді құрылғыларға бейімделген, толық функционалды корпоративтік веб-сайт жасау.'),
      space(1),
      h2('1.2 Жоба талаптары'),
      bullet('Үш тілді қолдау: қазақ, орыс, ағылшын'),
      bullet('Мобильді, планшет және компьютерге толық адаптация (Responsive Design)'),
      bullet('Парольмен қорғалған Админ панелі — мазмұнды тікелей сайттан өзгерту'),
      bullet('Серверсіз (serverless) сақтау жүйесі — GitHub API арқылы'),
      bullet('Байланыс формасы — хабарламаларды GitHub-қа сақтау'),
      bullet('Жылдам жүктеу, SEO оптимизация'),
      bullet('Күндізгі/Түнгі тема (Dark/Light mode)'),
      bullet('Тарих бөлімі — 1936 жылдан бастап диірменнің тарихы'),
      pb(),

      // ══════════════════════════════════════════
      // 2. ҚҰРАЛДАР
      // ══════════════════════════════════════════
      h1('2. ПАЙДАЛАНЫЛҒАН ҚҰРАЛДАР МЕН ТЕХНОЛОГИЯЛАР'),
      space(1),
      h2('2.1 Негізгі технологиялар'),
      space(1),
      twoCol('HTML5', 'Сайттың негізгі құрылымы — семантикалық тегтер, форм элементтері, мета тегтер'),
      space(0),
      twoCol('CSS3', 'Стильдер — Custom Properties (CSS Variables), Grid, Flexbox, анимациялар, медиа сұрауларымен толық адаптация'),
      space(0),
      twoCol('JavaScript (ES6+)', 'Клиенттік логика — DOM манипуляция, fetch API, localStorage, async/await'),
      space(0),
      twoCol('Node.js (Serverless)', 'Vercel функциялары — GitHub API арқылы файлдарды жазу/оқу'),
      space(0),
      twoCol('GitHub REST API v3', 'Деректерді сақтау — data.json және submissions.json файлдарын GitHub репозиторийіне жазу'),
      space(1),
      h2('2.2 Платформалар мен сервистер'),
      space(1),
      twoCol('GitHub', 'Код репозиторийі және мазмұн базасы (CMS ретінде). Репо: yeaska0/merke-agro'),
      space(0),
      twoCol('Vercel', 'Тегін хостинг платформасы — автоматты CI/CD деплой, serverless функциялар'),
      space(0),
      twoCol('WebStorm / VS Code', 'Код жазуға арналған IDE — синтаксис бөлектеу, автотолықтыру'),
      space(0),
      twoCol('Git', 'Нұсқа бақылау жүйесі — барлық өзгерістер git commit арқылы сақталды'),
      space(0),
      twoCol('iTerm / Terminal', 'Командалар жолы — git push, npm команд, файлдарды көшіру'),
      space(1),
      h2('2.3 Негізгі npm пакеттері'),
      bullet('docx — Word файлдарын программалық жасауға арналған кітапхана'),
      bullet('(Клиенттік жағында npm пакеттері жоқ — таза Vanilla JS пайдаланылды)'),
      pb(),

      // ══════════════════════════════════════════
      // 3. ЖОБА ҚҰРЫЛЫМЫ
      // ══════════════════════════════════════════
      h1('3. ЖОБА ҚҰРЫЛЫМЫ'),
      p('Сайт файлдары ~/merke-agro-site/ папкасында орналасқан. Папка құрылымы төмендегідей:'),
      space(1),
      codeBlock([
        'merke-agro-site/',
        '├── index.html          ← Бас бет (барлық бөлімдер бір файлда)',
        '├── package.json        ← {"type":"module"} — ESM модулі',
        '├── css/',
        '│   └── main.css        ← Барлық стильдер (1 файл)',
        '├── js/',
        '│   ├── data.js         ← Әдепкі деректер (DEF объекті)',
        '│   └── app.js          ← Барлық логика (render, admin, save...)',
        '└── api/',
        '    ├── save.js         ← Vercel function: data.json сақтау',
        '    └── submit.js       ← Vercel function: форм хабарламаларын сақтау',
      ]),
      space(1),
      p('GitHub репозиторийінде қосымша файлдар:'),
      codeBlock([
        'yeaska0/merke-agro  (GitHub репозиторийі)',
        '├── data.json           ← Сайт мазмұны (CMS деректері)',
        '└── submissions.json    ← Форм арқылы жіберілген хабарламалар',
      ]),
      space(1),
      infoBox('Маңызды архитектуралық шешім', 'Сайт «Single Page Application» (SPA) принципімен жасалды — барлық бөлімдер бір index.html файлында. JavaScript data.json-ды GitHub raw URL арқылы жүктеп, DOM-ға рендерлейді. Бұл деплойды жеңілдетеді және хостингке қосымша шығын кетпейді.'),
      pb(),

      // ══════════════════════════════════════════
      // 4. 1-ҚАДАМ: GIT
      // ══════════════════════════════════════════
      h1('4. 1-ҚАДАМ: GIT РЕПОЗИТОРИЙІН ДАЙЫНДАУ'),
      p('Жұмысты бастамас бұрын жергілікті папка мен GitHub репозиторийін орнаттым.'),
      space(1),
      h2('4.1 Жергілікті папка жасау'),
      codeBlock([
        '# Үй каталогында жоба папкасын жасадым',
        'mkdir ~/merke-agro-site',
        'cd ~/merke-agro-site',
        '',
        '# Ішкі папкаларды жасадым',
        'mkdir css js api',
        '',
        '# Git репозиторийін инициализациялым',
        'git init',
        'git branch -M main',
      ]),
      space(1),
      h2('4.2 GitHub репозиторийін жасау'),
      p('GitHub.com сайтында жаңа репозиторий жасадым:'),
      num('github.com сайтына кіріп, «New repository» батырмасын баστым'),
      num('Атауы: merke-agro, Visibility: Public (жалпыға ашық) деп белгіледім'),
      num('«Create repository» батырмасын баستым'),
      num('Жергілікті репоны GitHub-қа байладым:'),
      space(1),
      codeBlock([
        'git remote add origin https://github.com/yeaska0/merke-agro.git',
        'git push -u origin main',
      ]),
      space(1),
      h2('4.3 package.json жасау'),
      p('Vercel serverless функциялары ESM форматында жазылғандықтан, package.json-да type:module белгіледім:'),
      codeBlock([
        '// package.json',
        '{',
        '  "type": "module"',
        '}',
      ]),
      pb(),

      // ══════════════════════════════════════════
      // 5. 2-ҚАДАМ: HTML
      // ══════════════════════════════════════════
      h1('5. 2-ҚАДАМ: HTML — index.html ФАЙЛЫН ЖАСАУ'),
      p('index.html — сайттың жалғыз HTML файлы. Онда барлық бөлімдер орналасқан: навигация, hero, ферма туралы, тарих, өнімдер, команда, жаңалықтар, сертификаттар, FAQ, байланыс, футер, админ панелі.'),
      space(1),
      h2('5.1 HTML файлының жалпы құрылымы'),
      codeBlock([
        '<!DOCTYPE html>',
        '<html lang="kk">',
        '<head>',
        '  <meta charset="UTF-8"/>',
        '  <meta name="viewport" content="width=device-width,initial-scale=1.0"/>',
        '  <title>АСТЫҚ МЕРКЕ</title>',
        '  <link rel="stylesheet" href="css/main.css"/>',
        '</head>',
        '<body>',
        '',
        '  <!-- NAV — жоғарғы навигация -->',
        '  <nav id="navbar"> ... </nav>',
        '',
        '  <!-- HERO — бас бөлім -->',
        '  <section id="home" class="hero"> ... </section>',
        '',
        '  <!-- ABOUT — ферма туралы -->',
        '  <section id="about" class="about-bg"> ... </section>',
        '',
        '  <!-- STATS BAR — статистика жолағы -->',
        '  <div class="sbar"> ... </div>',
        '',
        '  <!-- HISTORY — 1936-дан бастап тарих -->',
        '  <section id="history" class="history-bg"> ... </section>',
        '',
        '  <!-- PRODUCTS — өнімдер -->',
        '  <section id="products"> ... </section>',
        '',
        '  <!-- WHY US — неліктен біз? -->',
        '  <section id="why" class="why-bg"> ... </section>',
        '',
        '  <!-- TEAM — команда -->',
        '  <section id="team"> ... </section>',
        '',
        '  <!-- GALLERY — фото галерея -->',
        '  <section id="gallery" class="gal-bg"> ... </section>',
        '',
        '  <!-- NEWS — жаңалықтар -->',
        '  <section id="news" class="news-bg"> ... </section>',
        '',
        '  <!-- CERTS — сертификаттар -->',
        '  <section id="certs"> ... </section>',
        '',
        '  <!-- FAQ — жиі қойылатын сұрақтар -->',
        '  <section id="faq"> ... </section>',
        '',
        '  <!-- CONTACT — байланыс + форм -->',
        '  <section id="contact"> ... </section>',
        '',
        '  <!-- FOOTER — футер -->',
        '  <footer> ... </footer>',
        '',
        '  <!-- ADMIN FAB — ⚙️ батырмасы -->',
        '  <button class="afab" onclick="showLogin()">⚙️</button>',
        '',
        '  <!-- LOGIN MODAL — кіру терезесі -->',
        '  <div class="mover" id="loginModal"> ... </div>',
        '',
        '  <!-- ADMIN PANEL — толық админ панелі -->',
        '  <div class="apanel" id="adminPanel"> ... </div>',
        '',
        '  <!-- SCRIPTS -->',
        '  <script src="js/data.js"></script>',
        '  <script src="js/app.js"></script>',
        '</body>',
        '</html>',
      ]),
      space(1),
      h2('5.2 Навигация блогы'),
      p('Навигация «sticky» (жоғарыда бекітілген) болуы үшін position:fixed пайдаландым. Мобильді үшін ☰ бургер батырмасы қосылды:'),
      codeBlock([
        '<nav id="navbar">',
        '  <div class="nav-inner">',
        '    <!-- Логотип -->',
        '    <div class="logo" onclick="goTo(\'home\')">',
        '      <div class="logo-icon">🌾</div>',
        '      <div class="logo-text">',
        '        <span class="ln lbrand1">АСТЫҚ</span>',
        '        <span class="ls lbrand2">МЕРКЕ</span>',
        '      </div>',
        '    </div>',
        '',
        '    <!-- Навигация сілтемелері -->',
        '    <ul class="nav-links">',
        '      <li><a onclick="goTo(\'about\')"  id="nl1">Ферма туралы</a></li>',
        '      <li><a onclick="goTo(\'history\')" id="nl-hist">Тарих</a></li>',
        '      <li><a onclick="goTo(\'products\')" id="nl2">Өнімдер</a></li>',
        '      <li><a onclick="goTo(\'team\')"    id="nl3">Команда</a></li>',
        '      <li><a onclick="goTo(\'news\')"    id="nl4">Жаңалықтар</a></li>',
        '      <li><a onclick="goTo(\'faq\')"     id="nl5">FAQ</a></li>',
        '      <li><a onclick="goTo(\'contact\')" id="nl6">Байланыс</a></li>',
        '    </ul>',
        '',
        '    <!-- Оң жақ: тіл, тема, байланыс, бургер -->',
        '    <div class="nav-right">',
        '      <div class="lang-btns">',
        '        <button class="lbtn active" onclick="setLang(\'kk\')">ҚАЗ</button>',
        '        <button class="lbtn"        onclick="setLang(\'ru\')">РУС</button>',
        '        <button class="lbtn"        onclick="setLang(\'en\')">ENG</button>',
        '      </div>',
        '      <button class="dark-toggle" onclick="toggleDark()" id="dark-btn">🌙</button>',
        '      <button class="nav-cta" onclick="goTo(\'contact\')" id="nl-cta">Хабарласу</button>',
        '      <button class="nav-burger" onclick="toggleMobileNav()" id="nav-burger">☰</button>',
        '    </div>',
        '  </div>',
        '</nav>',
      ]),
      space(1),
      h2('5.3 Тарих бөлімі (Timeline)'),
      p('1936 жылдан бастап диірменнің тарихын «timeline» форматында сипаттадым — 8 тарихи оқиға:'),
      codeBlock([
        '<section id="history" class="history-bg">',
        '  <div class="container">',
        '    <span class="stag">📜 Тарих</span>',
        '    <h2 class="stitle">Астық Мерке тарихы</h2>',
        '    <p class="sdesc">1936 жылдан бастап — Мерке ауданының өнеркәсіптік мұрасы</p>',
        '',
        '    <div class="hist-timeline">',
        '      <div class="ht-item">',
        '        <div class="ht-year">1936</div>',
        '        <div class="ht-dot"></div>',
        '        <div class="ht-card">',
        '          <div class="ht-icon">🏭</div>',
        '          <h4>Диірмен негізі қаланды</h4>',
        '          <p>Мерке темір жол станциясының солтүстік бөлігінде...</p>',
        '        </div>',
        '      </div>',
        '      <!-- 1944, 1946, 1961, 1993, 1994, 1995, Қазір -->',
        '    </div>',
        '  </div>',
        '</section>',
      ]),
      space(1),
      h2('5.4 Админ панелі (HTML бөлігі)'),
      p('Админ панелі — беттің үстіне жабылатын толық экранды overlay. Ол екі бөліктен тұрады: сол жақ sidebar (навигация) және оң жақ мазмұн (редактор):'),
      codeBlock([
        '<!-- ⚙️ батырмасы — кез келген жерде көрінеді -->',
        '<button class="afab" onclick="showLogin()" title="Админ панелі">⚙️</button>',
        '',
        '<!-- Кіру терезесі -->',
        '<div class="mover" id="loginModal">',
        '  <div class="mbox">',
        '    <div class="mbox-icon">🔐</div>',
        '    <h2>Админ панелі</h2>',
        '    <input type="password" id="pwdinput" placeholder="••••••••"',
        '           onkeydown="if(event.key===\'Enter\')doLogin()"/>',
        '    <div class="merr" id="merr"></div>',
        '    <div class="mbtns">',
        '      <button class="bconf" onclick="doLogin()">Кіру</button>',
        '      <button class="bcanc" onclick="hideLogin()">Болдырмау</button>',
        '    </div>',
        '  </div>',
        '</div>',
        '',
        '<!-- Толық экранды админ панелі -->',
        '<div class="apanel" id="adminPanel">',
        '  <div class="aside">  <!-- Сол жақ sidebar -->',
        '    <div class="anav">',
        '      <div class="ani" onclick="showSec(\'dash\')">📊 Дашборд</div>',
        '      <div class="ani" onclick="showSec(\'farm\')">🏭 Ферма</div>',
        '      <div class="ani" onclick="showSec(\'astats\')">📈 Статистика</div>',
        '      <div class="ani" onclick="showSec(\'aprods\')">🛍️ Өнімдер</div>',
        '      <div class="ani" onclick="showSec(\'ateam\')">👥 Команда</div>',
        '      <div class="ani" onclick="showSec(\'anews\')">📰 Жаңалықтар</div>',
        '      <div class="ani" onclick="showSec(\'afaq\')">❓ FAQ</div>',
        '      <div class="ani" onclick="showSec(\'acont\')">📞 Байланыс</div>',
        '      <div class="ani" onclick="showSec(\'settings\')">⚙️ Баптаулар</div>',
        '      <div class="ani" onclick="showSec(\'msgs\')">💬 Хабарламалар</div>',
        '    </div>',
        '  </div>',
        '  <div class="amain">  <!-- Оң жақ мазмұн -->',
        '    <!-- Әр бөлім үшін .asec div-тері -->',
        '  </div>',
        '</div>',
      ]),
      pb(),

      // ══════════════════════════════════════════
      // 6. CSS
      // ══════════════════════════════════════════
      h1('6. 3-ҚАДАМ: CSS — main.css СТИЛЬДЕР'),
      p('Барлық стильдер css/main.css файлына жинақталды. Файл 380+ жолдан тұрады және CSS Custom Properties (айнымалылар) жүйесі арқылы тема ауыстыру мүмкіндігі іске асырылды.'),
      space(1),
      h2('6.1 CSS айнымалылары (Custom Properties)'),
      p('Барлық түстер мен мәндер :root айнымалыларда сақталды, бұл Dark mode-ті бір жерден ауыстыруды жеңілдетті:'),
      codeBlock([
        ':root {',
        '  --primary:       #2e7d32;  /* Негізгі жасыл */ыы',
        '  --primary-dark:  #1b5e20;  /* Қоюрақ жасыл */',
        '  --primary-light: #66bb6a;  /* Ашық жасыл */',
        '  --accent:        #ff8f00;  /* Сарғыш-қоңыр */',
        '  --bg:            #ffffff;  /* Фон */',
        '  --bg2:           #f8fdf8;  /* Екінші фон */',
        '  --gr:            #f0f7f0;  /* Жасыл-ақ фон */',
        '  --card:          #ffffff;  /* Карточка фоны */',
        '  --border:        #e0ece0;  /* Шекара */',
        '  --text:          #1a1a1a;  /* Негізгі мәтін */',
        '  --mu:            #5a6a5a;  /* Мутед мәтін */',
        '  --shadow:        0 4px 20px rgba(0,0,0,.08);',
        '  --radius:        16px;',
        '  --transition:    all .25s cubic-bezier(.4,0,.2,1);',
        '}',
        '',
        '/* Dark mode — body.dark класы қосылғанда */',
        'body.dark {',
        '  --bg:    #0f1a0f;',
        '  --bg2:   #131f13;',
        '  --card:  #1a2a1a;',
        '  --text:  #e8f5e9;',
        '  --border:#2a3a2a;',
        '}',
      ]),
      space(1),
      h2('6.2 Навигация стильдері'),
      codeBlock([
        '#navbar {',
        '  position: fixed;        /* Жоғарыда бекітілген */',
        '  top: 0; left: 0; right: 0;',
        '  z-index: 1000;',
        '  background: rgba(255,255,255,.85);',
        '  backdrop-filter: blur(16px); /* Шыны эффекті */',
        '  border-bottom: 1px solid var(--border);',
        '}',
        '',
        '.nav-inner {',
        '  max-width: 1300px;',
        '  margin: 0 auto;',
        '  padding: .9rem 2rem;',
        '  display: flex;',
        '  align-items: center;',
        '  gap: 2rem;',
        '}',
      ]),
      space(1),
      h2('6.3 Hero бөлімі'),
      codeBlock([
        '.hero {',
        '  min-height: 100vh;',
        '  background: linear-gradient(',
        '    135deg,',
        '    var(--bg) 0%,',
        '    var(--gr) 40%,',
        '    rgba(102,187,106,.07) 100%',
        '  );',
        '  display: flex;',
        '  align-items: center;',
        '  padding: 6rem 2rem 4rem;',
        '}',
        '',
        '.hero-inner {',
        '  max-width: 1200px;',
        '  margin: 0 auto;',
        '  display: grid;',
        '  grid-template-columns: 1fr 1fr; /* 2 баған */',
        '  gap: 4rem;',
        '  align-items: center;',
        '}',
      ]),
      space(1),
      h2('6.4 Responsive Design (Адаптация)'),
      p('Сайт үш деңгейлі breakpoint жүйесін пайдаланады:'),
      codeBlock([
        '/* Планшет: 1024px-тен кіші */',
        '@media(max-width: 1024px) {',
        '  .nav-links { display: none; }  /* Мәзір жасырылады */',
        '  .nav-burger { display: flex; } /* Бургер пайда болады */',
        '  .hero-inner { grid-template-columns: 1fr; } /* 1 баған */',
        '  #navbar.nav-open .nav-links {  /* Бургер ашылса */',
        '    display: flex;',
        '    flex-direction: column;',
        '    position: absolute;',
        '    top: 100%; left: 0; right: 0;',
        '    background: var(--bg);',
        '  }',
        '}',
        '',
        '/* Планшет кіші: 768px */',
        '@media(max-width: 768px) {',
        '  .wgrid, .tgrid { grid-template-columns: repeat(2, 1fr); }',
        '  section { padding: 60px 1.2rem; }',
        '}',
        '',
        '/* Телефон: 640px-тен кіші */',
        '@media(max-width: 640px) {',
        '  .pgrid, .ngrid, .tgrid { grid-template-columns: 1fr; }',
        '  .hero h1 { font-size: clamp(1.8rem, 7vw, 2.6rem); }',
        '  .fbot { flex-direction: column; text-align: center; }',
        '}',
      ]),
      space(1),
      h2('6.5 Тарих Timeline CSS'),
      codeBlock([
        '.hist-timeline {',
        '  position: relative;',
        '  max-width: 900px;',
        '  margin: 0 auto;',
        '}',
        '',
        '/* Тік сызық — timeline осі */',
        '.hist-timeline::before {',
        '  content: "";',
        '  position: absolute;',
        '  left: 90px; top: 0; bottom: 0;',
        '  width: 2px;',
        '  background: linear-gradient(180deg, var(--primary), var(--accent));',
        '}',
        '',
        '.ht-item {',
        '  display: flex;',
        '  align-items: flex-start;',
        '  gap: 1.5rem;',
        '  margin-bottom: 2.5rem;',
        '}',
        '',
        '.ht-year { width: 75px; font-weight: 800; color: var(--primary); }',
        '',
        '.ht-dot {',
        '  width: 14px; height: 14px;',
        '  border-radius: 50%;',
        '  background: var(--primary);',
        '  border: 3px solid var(--bg);',
        '  box-shadow: 0 0 0 2px var(--primary);',
        '}',
      ]),
      pb(),

      // ══════════════════════════════════════════
      // 7. DATA.JS
      // ══════════════════════════════════════════
      h1('7. 4-ҚАДАМ: JAVASCRIPT — data.js ДЕРЕКТЕР'),
      p('js/data.js файлы — сайттың барлық мазмұнын қамтитын DEF (Default) объектісін жариялайды. Бұл объект GitHub-тан data.json жүктелмеген жағдайда резервтік деректер ретінде пайдаланылады.'),
      space(1),
      codeBlock([
        '// js/data.js — Әдепкі деректер',
        'const DEF = {',
        '',
        '  // Hero бөлімі',
        '  hero: {',
        '    kk: {',
        '      badge: "Қазақстанның табиғи өнімдері",',
        '      desc:  "Таза табиғат, заманауи технология және ұрпақтан ұрпаққа жеткен тәжірибе..."',
        '    },',
        '    ru: { badge: "Натуральные продукты Казахстана", desc: "..." },',
        '    en: { badge: "Natural Products of Kazakhstan",  desc: "..." }',
        '  },',
        '',
        '  // Ферма туралы',
        '  about: {',
        '    year: "2004", area: "5000",',
        '    kk: { tag: "Ферма туралы", title: "Мерке — табиғат пен технологияның үйлесімі",',
        '          feats: [{ i: "🌾", t: "Заманауи техника", d: "Еуропалық стандарт" }, ...]',
        '    },',
        '    ru: { ... }, en: { ... }',
        '  },',
        '',
        '  // Статистика жолағы',
        '  stats: [',
        '    { num: "5000+", kk: "га егістік жер", ru: "га пахотных земель", en: "ha arable land" },',
        '    { num: "20+",   kk: "жыл тәжірибе",  ru: "лет опыта",          en: "years experience" },',
        '    { num: "100%",  kk: "табиғи өнім",   ru: "натуральный продукт",en: "natural product" },',
        '    { num: "500+",  kk: "мал басы",       ru: "голов скота",        en: "head of livestock" }',
        '  ],',
        '',
        '  // Өнімдер',
        '  products: [',
        '    { icon: "🌾", color: "grain",',
        '      kk: { title: "Астық өнімдері", desc: "...", tags: "Бидай,Арпа,Сұлы", price: "65₸/кг" },',
        '      ru: { ... }, en: { ... }',
        '    },',
        '    { icon: "🥩", color: "meat",  kk: {...}, ru: {...}, en: {...} },',
        '    { icon: "🥛", color: "dairy", kk: {...}, ru: {...}, en: {...} }',
        '  ],',
        '',
        '  // FAQ',
        '  faq: [',
        '    { kk: { q: "Өнімдерді қайдан сатып алуға болады?", a: "..." }, ru: {...}, en: {...} },',
        '    ...',
        '  ],',
        '',
        '  // Байланыс',
        '  contact: {',
        '    phone1: "+7 (726) 234-56-78", phone2: "+7 (700) 123-45-67",',
        '    email1: "info@astykmerke.kz", email2: "sales@astykmerke.kz",',
        '    addr_kk: "Жамбыл облысы, Мерке ауданы, Астық Мерке кешені",',
        '    wd: "Дүйсенбі–Жұма: 08:00–18:00", ws: "Сенбі: 09:00–14:00"',
        '  },',
        '',
        '  // Сайт баптаулары',
        '  siteSettings: {',
        '    brand1: "АСТЫҚ", brand2: "МЕРКЕ",',
        '    footerCopy_kk: "© 2026 Астық Мерке. Барлық құқықтар қорғалған",',
        '    footerCopy_ru: "© 2026 Астық Мерке. Все права защищены",',
        '    footerCopy_en: "© 2026 Astyk Merke. All rights reserved"',
        '  }',
        '};',
      ]),
      pb(),

      // ══════════════════════════════════════════
      // 8. APP.JS
      // ══════════════════════════════════════════
      h1('8. 5-ҚАДАМ: JAVASCRIPT — app.js ҚОСЫМША ЛОГИКАСЫ'),
      p('js/app.js — сайттың барлық логикасы жинақталған негізгі файл (790+ жол). Ол мына жүйелерді қамтиды:'),
      bullet('Деректерді жүктеу (loadData) → рендерлеу (render)'),
      bullet('Тіл ауыстыру (setLang) — KK / RU / EN'),
      bullet('Навигация (goTo) — smooth scroll'),
      bullet('Күн/Түн тема (toggleDark)'),
      bullet('Байланыс формасын жіберу (submitForm)'),
      bullet('Админ панелі — кіру, секциялар, редактор'),
      bullet('GitHub-қа сақтау (save → /api/save)'),
      space(1),
      h2('8.1 Инициализация және деректерді жүктеу'),
      codeBlock([
        '// ===== КҮЙЛЕР (STATE) =====',
        'let D = null;       // Белсенді деректер объекті',
        'let L = "kk";      // Ағымдағы тіл',
        'let adminLang = "kk";',
        'const PASS = "merke2026";',
        'const REPO_OWNER = "yeaska0";',
        'const REPO_NAME  = "merke-agro";',
        '',
        '// ===== ИНИЦИАЛИЗАЦИЯ =====',
        'document.addEventListener("DOMContentLoaded", () => {',
        '  loadData();',
        '  const saved = localStorage.getItem("merke_lang");',
        '  if (saved) L = saved;',
        '  if (localStorage.getItem("merke_dark") === "1") {',
        '    document.body.classList.add("dark");',
        '  }',
        '});',
        '',
        '// ===== ДЕРЕКТЕРДІ ЖҮКТЕУ =====',
        'async function loadData() {',
        '  try {',
        '    // Cache-bust үшін ?t=timestamp қосылды',
        '    const url = `https://raw.githubusercontent.com/${REPO_OWNER}/${REPO_NAME}/main/data.json?t=${Date.now()}`;',
        '    const r = await fetch(url);',
        '    if (r.ok) D = await r.json();',
        '    else D = deepClone(DEF);',
        '  } catch {',
        '    D = deepClone(DEF);',
        '  }',
        '  render();',
        '}',
        '',
        'function deepClone(obj) {',
        '  return JSON.parse(JSON.stringify(obj));',
        '}',
      ]),
      space(1),
      h2('8.2 Рендерлеу жүйесі'),
      p('render() функциясы шақырылған кезде барлық бөлімдер қайта сызылады. Бұл тіл ауысқанда немесе деректер өзгергенде жұмыс жасайды:'),
      codeBlock([
        'function render() {',
        '  renderHero();',
        '  renderAbout();',
        '  renderStatsBar();',
        '  renderProducts();',
        '  renderWhy();',
        '  renderTeam();',
        '  renderNews();',
        '  renderCerts();',
        '  renderFaq();',
        '  renderContact();',
        '  renderFooter();',
        '  updateLangUI();  // Тіл батырмаларын жаңарту',
        '}',
        '',
        '// Hero бөлімін рендерлеу',
        'function renderHero() {',
        '  const h  = D.hero;',
        '  const ss = D.siteSettings || {};',
        '  const b1 = ss.brand1 || "АСТЫҚ";',
        '  const b2 = ss.brand2 || "МЕРКЕ";',
        '',
        '  el("hbadge").textContent    = t(h).badge || "";',
        '  el("hero-title").innerHTML  = `<span>${b1}</span> ${b2}`;',
        '  el("hero-desc").textContent = t(h).desc  || "";',
        '}',
        '',
        '// Тіл аудармашысы',
        'function t(obj) {',
        '  return obj[L] || obj["kk"] || {};',
        '}',
      ]),
      space(1),
      h2('8.3 Тіл ауыстыру — маңызды қате және шешімі'),
      p('Жасау барысында критикалық қате табылды: render() → setLang() → render() шексіз рекурсия (Maximum call stack size exceeded). Шешімі — updateLangUI() жеке функциясын жасау:'),
      codeBlock([
        '// ❌ ҚАТЕ нұсқа — шексіз рекурсия:',
        '// function render()   { ... setLang(L); }  ← setLang шақырады',
        '// function setLang(l) { L=l; render(); }   ← render шақырады',
        '',
        '// ✅ ДҰРЫС нұсқа — updateLangUI бөлінді:',
        'function render() {',
        '  renderHero(); /* ... */  renderFooter();',
        '  updateLangUI(); // ← setLang емес!',
        '}',
        '',
        'function updateLangUI() {',
        '  // Тіл батырмаларын белсендіру',
        '  document.querySelectorAll(".lbtn").forEach((b, i) => {',
        '    b.classList.toggle("active", ["kk","ru","en"][i] === L);',
        '  });',
        '  // Навигация мәтіндерін жаңарту',
        '  el("nl1").textContent = {kk:"Ферма туралы", ru:"О ферме", en:"About"}[L];',
        '  // ...барлық мәтіндер',
        '}',
        '',
        'function setLang(lang) {',
        '  L = lang;',
        '  localStorage.setItem("merke_lang", L);',
        '  render(); // тек бір рет шақырады',
        '}',
      ]),
      space(1),
      h2('8.4 Админ панелі логикасы'),
      codeBlock([
        '// Кіру',
        'function showLogin() {',
        '  el("loginModal").classList.add("show");',
        '  setTimeout(() => el("pwdinput").focus(), 100);',
        '}',
        '',
        'function doLogin() {',
        '  if (el("pwdinput").value === PASS) {',
        '    hideLogin();',
        '    openAdmin();',
        '  } else {',
        '    el("merr").textContent = {kk:"Қате пароль", ru:"Неверный пароль", en:"Wrong password"}[L];',
        '  }',
        '}',
        '',
        '// Секцияны ауыстыру',
        'function showSec(id) {',
        '  document.querySelectorAll(".asec").forEach(s => s.classList.remove("active"));',
        '  document.querySelectorAll(".ani") .forEach(n => n.classList.remove("active"));',
        '  el(`sec-${id}`).classList.add("active");',
        '}',
        '',
        '// Ферма деректерін сақтау',
        'function saveFarm() {',
        '  const al = adminLang;',
        '  if (!D.hero[al]) D.hero[al] = {};',
        '  D.hero[al].badge = el("f-badge").value;',
        '  D.hero[al].desc  = el("f-hdesc").value;',
        '  D.about.year     = el("f-year").value;',
        '  D.about.area     = el("f-area").value;',
        '  render();',
        '  save("farm-saved"); // GitHub-қа жіберу',
        '}',
      ]),
      space(1),
      h2('8.5 GitHub-қа сақтау функциясы'),
      codeBlock([
        '// GitHub-қа сақтау — /api/save serverless арқылы',
        'async function save(savedId) {',
        '  const el2 = savedId ? document.getElementById(savedId) : null;',
        '  if (el2) { el2.textContent = "⏳ Жариялануда..."; el2.classList.add("show"); }',
        '',
        '  try {',
        '    const r = await fetch("/api/save", {',
        '      method: "POST",',
        '      headers: { "Content-Type": "application/json" },',
        '      body: JSON.stringify(D)  // Барлық D объектісін жіберу',
        '    });',
        '    const json = await r.json();',
        '    if (!json.success) throw new Error(json.error || "Қате");',
        '',
        '    render(); // Сайтты бірден жаңарту',
        '    if (el2) {',
        '      el2.textContent = "✅ Сайтқа жарияланды!";',
        '      setTimeout(() => { el2.classList.remove("show"); }, 4000);',
        '    }',
        '  } catch(e) {',
        '    if (el2) el2.classList.remove("show");',
        '    alert("Қате: " + e.message);',
        '  }',
        '}',
      ]),
      pb(),

      // ══════════════════════════════════════════
      // 9. API/SAVE.JS
      // ══════════════════════════════════════════
      h1('9. 6-ҚАДАМ: SERVERLESS API — api/save.js'),
      p('api/save.js — Vercel serverless функциясы. Клиенттен D объектісін алып, оны base64-ке кодтап, GitHub REST API арқылы data.json файлын жаңартады. GITHUB_TOKEN тек серверде сақталады — клиент жағында ешқашан көрінбейді.'),
      space(1),
      codeBlock([
        '// api/save.js — Vercel Serverless Function',
        'export default async function handler(req, res) {',
        '  // CORS тақырыптары',
        '  res.setHeader("Access-Control-Allow-Origin", "*");',
        '  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");',
        '  res.setHeader("Access-Control-Allow-Headers", "Content-Type");',
        '',
        '  if (req.method === "OPTIONS") return res.status(200).end();',
        '  if (req.method !== "POST")',
        '    return res.status(405).json({ error: "Method not allowed" });',
        '',
        '  // Vercel орта айнымалысынан токенді оқу',
        '  const token = process.env.GITHUB_TOKEN;',
        '  if (!token)',
        '    return res.status(500).json({ error: "GITHUB_TOKEN not configured" });',
        '',
        '  const owner   = "yeaska0";',
        '  const repo    = "merke-agro";',
        '  const file    = "data.json";',
        '  const apiBase = `https://api.github.com/repos/${owner}/${repo}/contents/${file}`;',
        '',
        '  const headers = {',
        '    "Authorization": `token ${token}`,',
        '    "Accept":        "application/vnd.github.v3+json",',
        '    "Content-Type":  "application/json",',
        '  };',
        '',
        '  try {',
        '    // 1. Ағымдағы файлдың SHA-сын алу (жаңарту үшін керек)',
        '    const infoRes = await fetch(apiBase, { headers });',
        '    const info    = await infoRes.json();',
        '    if (info.message) return res.status(500).json({ error: info.message });',
        '',
        '    // 2. Жаңа мазмұнды base64-ке кодтау',
        '    const content = Buffer',
        '      .from(JSON.stringify(req.body, null, 2))',
        '      .toString("base64");',
        '',
        '    // 3. GitHub API-ға PUT сұранысы',
        '    const putRes = await fetch(apiBase, {',
        '      method: "PUT",',
        '      headers,',
        '      body: JSON.stringify({',
        '        message: "Admin update " + new Date().toISOString(),',
        '        content,',
        '        sha: info.sha, // SHA болмаса GitHub қабылдамайды',
        '      }),',
        '    });',
        '    const put = await putRes.json();',
        '',
        '    if (!put.content)',
        '      return res.status(500).json({ error: put.message || "GitHub push failed" });',
        '',
        '    return res.status(200).json({ success: true });',
        '  } catch (e) {',
        '    return res.status(500).json({ error: e.message });',
        '  }',
        '}',
      ]),
      pb(),

      // ══════════════════════════════════════════
      // 10. API/SUBMIT.JS
      // ══════════════════════════════════════════
      h1('10. 7-ҚАДАМ: SERVERLESS API — api/submit.js'),
      p('api/submit.js — байланыс формасы арқылы жіберілген хабарламаларды submissions.json файлына жазады. Принципі save.js-тікіндей, бірақ деректерді қосып жазады (append).'),
      space(1),
      codeBlock([
        '// api/submit.js — форм хабарламаларын сақтау',
        'export default async function handler(req, res) {',
        '  /* ... CORS тақырыптары ... */',
        '',
        '  const token   = process.env.GITHUB_TOKEN;',
        '  const apiBase = "https://api.github.com/repos/yeaska0/merke-agro/contents/submissions.json";',
        '  const headers = { "Authorization": `token ${token}`, ... };',
        '',
        '  try {',
        '    // 1. Ағымдағы submissions.json-ды оқу',
        '    let submissions = [];',
        '    let sha = null;',
        '    const infoRes = await fetch(apiBase, { headers });',
        '    if (infoRes.ok) {',
        '      const info = await infoRes.json();',
        '      sha = info.sha;',
        '      // base64-тен JSON-ға айналдыру',
        '      const decoded = Buffer.from(info.content, "base64").toString("utf8");',
        '      submissions = JSON.parse(decoded);',
        '    }',
        '',
        '    // 2. Жаңа хабарламаны қосу',
        '    submissions.push({',
        '      ...req.body,',
        '      date: new Date().toISOString(),',
        '    });',
        '',
        '    // 3. GitHub-қа жазу',
        '    const content = Buffer',
        '      .from(JSON.stringify(submissions, null, 2))',
        '      .toString("base64");',
        '    const body = { message: "New submission", content };',
        '    if (sha) body.sha = sha;',
        '',
        '    await fetch(apiBase, { method: "PUT", headers, body: JSON.stringify(body) });',
        '',
        '    return res.status(200).json({ success: true });',
        '  } catch (e) {',
        '    return res.status(500).json({ error: e.message });',
        '  }',
        '}',
      ]),
      pb(),

      // ══════════════════════════════════════════
      // 11. GITHUB
      // ══════════════════════════════════════════
      h1('11. 8-ҚАДАМ: GITHUB-ҚА ЖАРИЯЛАУ'),
      p('Барлық файлдар дайын болғаннан кейін оларды GitHub репозиторийіне жарияладым. Бұл процесс Vercel-дің автоматты CI/CD деплойын іске қосады.'),
      space(1),
      h2('11.1 Файлдарды жергілікті репоға көшіру'),
      codeBlock([
        '# Файлдарды жоба папкасына көшіру',
        'cp index.html    ~/merke-agro-site/index.html',
        'cp css/main.css  ~/merke-agro-site/css/main.css',
        'cp js/app.js     ~/merke-agro-site/js/app.js',
        'cp js/data.js    ~/merke-agro-site/js/data.js',
        'cp api/save.js   ~/merke-agro-site/api/save.js',
        'cp api/submit.js ~/merke-agro-site/api/submit.js',
      ]),
      space(1),
      h2('11.2 Git commit және push'),
      codeBlock([
        'cd ~/merke-agro-site',
        '',
        '# Барлық өзгерістерді индекске қосу',
        'git add -A',
        '',
        '# Commit жасау',
        'git commit -m "Initial: Астық Мерке сайты толық нұсқа"',
        '',
        '# GitHub-қа жіберу',
        'git push origin main',
      ]),
      space(1),
      h2('11.3 Кездескен мәселелер'),
      p('GitHub-қа push жасау кезінде бірнеше қате кездесті:'),
      bullet('fetch first қатесі — remote-да жергілікті репода жоқ commit болды. Шешімі: git pull --rebase origin main && git push'),
      bullet('GH013: Push Protection — ескі токен git тарихында сақталған болды. Шешімі: GitHub-тың bypass URL-ін пайдалану'),
      space(1),
      codeBlock([
        '# Remote-да жаңа commit болса:',
        'git pull --rebase origin main',
        'git push',
      ]),
      pb(),

      // ══════════════════════════════════════════
      // 12. VERCEL
      // ══════════════════════════════════════════
      h1('12. 9-ҚАДАМ: VERCEL-ДЕ ОРНАЛАСТЫРУ'),
      p('Vercel — тегін хостинг платформасы. GitHub репозиторийімен байланыстырылғаннан кейін, әр git push болғанда автоматты түрде жаңа деплой жасайды.'),
      space(1),
      h2('12.1 Vercel-де жоба жасау'),
      num('vercel.com сайтына кіріп, «Add New Project» батырмасын баستым'),
      num('GitHub аккаунтымды байладым: yeaska0'),
      num('Репозиторийді таңдадым: merke-agro'),
      num('Build Settings — Framework: «Other» (Vanilla JS, build керек емес)'),
      num('«Deploy» батырмасын баستым'),
      num('Vercel автоматты түрде деплой жасады: https://merke-agro.vercel.app'),
      space(1),
      h2('12.2 Vercel CI/CD процесі'),
      codeBlock([
        'git push origin main',
        '   ↓',
        'GitHub webhook → Vercel қабылдайды',
        '   ↓',
        'Vercel build (20-60 секунд)',
        '   ↓',
        'merke-agro.vercel.app жаңартылады',
      ]),
      space(1),
      infoBox('Маңызды', 'Vercel api/ папкасындағы .js файлдарды автоматты түрде Serverless функция ретінде таниды. package.json-дағы "type":"module" ESM → CommonJS ескертуін жою үшін қосылды.'),
      pb(),

      // ══════════════════════════════════════════
      // 13. ENV VARIABLES
      // ══════════════════════════════════════════
      h1('13. 10-ҚАДАМ: ОРТА АЙНЫМАЛЫЛАРЫ (ENVIRONMENT VARIABLES)'),
      p('api/save.js файлындағы GITHUB_TOKEN тек Vercel-дің серверінде сақталуы керек — клиент жағында ешқашан болмауы тиіс. Бұл қауіпсіздіктің негізгі принципі.'),
      space(1),
      h2('13.1 GitHub токенін жасау'),
      num('github.com → Settings → Developer Settings → Personal Access Tokens → Tokens (classic)'),
      num('«Generate new token (classic)» батырмасын баستым'),
      num('Scope: repo (толық репозиторий рұқсаты) белгіледім'),
      num('Expiration: No expiration (мерзімсіз) таңдадым'),
      num('Токенді көшірдім — ол бір рет ғана көрсетіледі'),
      space(1),
      h2('13.2 Vercel-де орта айнымалысын орнату'),
      num('vercel.com → merke-agro жобасы → Settings → Environment Variables'),
      num('Name: GITHUB_TOKEN деп жаздым'),
      num('Value: жасалған токенді қойдым'),
      num('Environment: Production, Preview, Development — үшеуін де белгіледім'),
      num('«Save» батырмасын бастым'),
      num('Vercel → Deployments → «Redeploy» арқылы жаңа деплой жасадым'),
      space(1),
      infoBox('Қауіпсіздік ескертуі', 'GITHUB_TOKEN ешқашан index.html, app.js, data.js немесе басқа клиенттік файлдарда болмауы керек. Ол тек Vercel орта айнымалысында және api/ функцияларында process.env.GITHUB_TOKEN арқылы оқылады.'),
      pb(),

      // ══════════════════════════════════════════
      // 14. ТЕСТІЛЕУ
      // ══════════════════════════════════════════
      h1('14. ТЕСТІЛЕУ ЖӘНЕ ҚАТЕЛЕРДІ ЖОЮ'),
      p('Сайтты жасау барысында бірнеше маңызды қате анықтап, жойдым:'),
      space(1),
      h2('14.1 Maximum call stack size exceeded'),
      p('Бұл — ең маңызды қате. render() → setLang() → render() шексіз рекурсия туғызды. Browser DevTools → Console арқылы анықталды.'),
      codeBlock([
        '// Қате: Uncaught RangeError: Maximum call stack size exceeded',
        '//',
        '// Себебі:',
        '// render() → ... → setLang(L)  // setLang шақырады',
        '// setLang() → render()          // render шақырады ← ШЕКСІЗ',
        '//',
        '// Шешімі: updateLangUI() функциясын жеке бөлу',
        '// render() → updateLangUI()     // render шақырмайды',
        '// setLang() → render()          // тек бір рет',
      ]),
      space(1),
      h2('14.2 Admin save жұмыс жасамады'),
      p('Сақтау батырмасын басқанда өзгерістер сайтта көрінбеді. DevTools → Network арқылы тексердім — /api/save {"success":true} қайтарды, бірақ render() шақырылмапты.'),
      codeBlock([
        '// Шешімі: save() функциясына render() қоспасын қостым',
        'async function save(savedId) {',
        '  // ...',
        '  if (!json.success) throw new Error(json.error);',
        '  render(); // ← осы жол жетіспей тұрған',
        '  if (el2) { el2.textContent = "✅ Сайтқа жарияланды!"; }',
        '}',
      ]),
      space(1),
      h2('14.3 DevTools арқылы тестілеу'),
      p('Safari браузерінде DevTools панелін Command+Option+I немесе Command+Option+C пернелері арқылы ашып, Console мен Network табтарын пайдаландым:'),
      bullet('Console → JavaScript қателерін анықтау'),
      bullet('Network → /api/save, /api/submit сұраныстарының жауаптарын тексеру'),
      bullet('Response tab → {"success":true} немесе {"error":"..."} хабарламаларын оқу'),
      space(1),
      h2('14.4 Мобильді тестілеу'),
      p('Мобильді адаптацияны MacBook-та DevTools → «Responsive Design Mode» (Command+Option+M) арқылы тексердім. Телефон (390px), планшет (768px), ноутбук (1280px) өлшемдерін тексердім.'),
      pb(),

      // ══════════════════════════════════════════
      // 15. ҚОРЫТЫНДЫ
      // ══════════════════════════════════════════
      h1('15. ҚОРЫТЫНДЫ'),
      p('«Астық Мерке» агро кешенінің веб-сайтын сәтті жасап, Vercel хостингіне орналастырдым. Сайт барлық алдын ала белгіленген талаптарды орындады:'),
      space(1),
      bullet('✅ Үш тілде жұмыс жасайды (қазақ, орыс, ағылшын)'),
      bullet('✅ Мобильді, планшет және компьютерге толық бейімделген'),
      bullet('✅ Парольмен қорғалған Админ панелі (merke2026)'),
      bullet('✅ Барлық мазмұн GitHub API арқылы сақталады — сервер жоқ'),
      bullet('✅ Байланыс формасы жұмыс жасайды'),
      bullet('✅ Dark/Light mode'),
      bullet('✅ 1936 жылдан бастап тарих timeline бөлімі'),
      bullet('✅ Сайт мекенжайы: https://merke-agro.vercel.app'),
      space(1),
      h2('Қолданылған технологиялар жиынтығы'),
      space(1),
      twoCol('Frontend', 'HTML5, CSS3 (Custom Properties, Grid, Flexbox), Vanilla JavaScript ES6+'),
      space(0),
      twoCol('Backend', 'Vercel Serverless Functions (Node.js ESM)'),
      space(0),
      twoCol('CMS', 'GitHub REST API v3 — data.json файлы арқылы'),
      space(0),
      twoCol('Hosting', 'Vercel (тегін, автоматты CI/CD)'),
      space(0),
      twoCol('Version Control', 'Git + GitHub (yeaska0/merke-agro)'),
      space(0),
      twoCol('IDE', 'WebStorm / VS Code, iTerm Terminal'),
      space(1),
      p('Бұл жоба — backend-сіз, тегін хостингте жұмыс жасайтын, толық функционалды корпоративтік веб-сайттың үлгісі. GitHub-ты CMS ретінде пайдалану тәсілі — заманауи «Jamstack» архитектурасының нақты іске асырылуы.'),
      space(2),
      new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [new TextRun({ text: '— Есеп аяқталды —', size: 22, font: 'Arial', color: '888888', italics: true })]
      }),
    ]
  }]
});

// ─── ЖАЗУ ───────────────────────────────────────────────────────────────────
const OUTPUT = '/Users/yerasyl/merke-agro-site/Астык_Мерке_Отчет.docx';
Packer.toBuffer(doc).then(buffer => {
  fs.writeFileSync(OUTPUT, buffer);
  console.log('✅ Файл жасалды:', OUTPUT);
}).catch(e => {
  console.error('❌ Қате:', e.message);
});
